/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.InetAddress;
import java.net.URL;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author KYJOK
 */
public class formUtama extends javax.swing.JFrame {

    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public formUtama() {
    //this.setUndecorated(true);
    //this.setResizable(false);
    this.setVisible(true);
        initComponents();
        //setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
//Koneksi ke database
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        
    }
        public String getnamepc(){ 
        String pc = new String();
        try {  
      InetAddress id = InetAddress.getLocalHost();
      pc = id.getHostName();
    } catch (UnknownHostException e) {  
    }
        return pc;
    }
        private void datatoweb(String a,String b,String c,String d){
        String login =" ";
        String nama =" ";
        
        try {
            
            String nim = a ;
            String namapc = b ;
            String status = c ;
            String saran = d ;
            //System.out.print(nim+' '+namapc);
            //String url = "http://labtif.poltek-kampar.ac.id/api/historydesktop?nim="+nim+"&namapc="+namapc+"&status="+status;
            String url = "http://localhost/wpu-login/api/historydesktop?nim="+nim+"&namapc="+namapc+"&status="+status;
            URL obj = new URL(url);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();
            // optional default is GET
            con.setRequestMethod("GET");
            //add request header
            con.setRequestProperty("User-Agent", "Mozilla/5.0");
            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();
            while ((inputLine = in .readLine()) != null) {
                response.append(inputLine);
            } in .close();
            JSONObject obj_JSONObject = new JSONObject(response.toString());
            JSONArray obj_JSONArray = obj_JSONObject.getJSONArray("status_");
            
            JSONObject Json_out = new JSONObject(response.toString());
            
            //System.out.println(obj_JSONArray);
            JSONObject obj_JSONObject2 = obj_JSONArray.getJSONObject(0);
            
            JSONArray address_components_array = obj_JSONObject2.getJSONArray("status2");
            
            JSONObject obj_JSONObject3 = address_components_array.getJSONObject(0);
            
            login = obj_JSONObject3.getString("status3");
            
            // System.out.println("Status Login Anda : " + obj_JSONObject3.getString("status3"));
                System.out.println(getnamepc());            
        } catch (Exception e) {
            System.err.println("Ini Error "+e);
        }
    }
        
    public String tanggal() {

      Date HariSekarang = new Date( );
      SimpleDateFormat ft = 
      new SimpleDateFormat ("E dd/MM/yyyy HH:mm:ss a");

      System.out.println( ft.format(HariSekarang));
      return ft.format(HariSekarang);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1923, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnim.setText("a");
        getContentPane().add(txtnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 200, 20));

        txtnama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnama.setText("a");
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 200, 20));

        txtpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Dekstop Logout.png"))); // NOI18N
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 90, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String login = " ";
        String active = " ";
        String nama = "";
        String saran = "";
        
        try {
            
            String nim = txtnim.getText();
            String password = txtpass.getText();
            System.out.print(nim+' '+password);
            //String url = "http://labtif.poltek-kampar.ac.id/api/logindesktop?nim="+nim+"&password="+password;
            String url = "http://localhost/wpu-login/api/logindesktop?nim="+nim+"&password="+password;
            URL obj = new URL(url);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();
            // optional default is GET
            con.setRequestMethod("GET");
            //add request header
            con.setRequestProperty("User-Agent", "Mozilla/5.0");
            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();
            while ((inputLine = in .readLine()) != null) {
                response.append(inputLine);
            } in .close();
            JSONObject obj_JSONObject = new JSONObject(response.toString());
            JSONArray obj_JSONArray = obj_JSONObject.getJSONArray("status_");
            
            JSONObject Json_out = new JSONObject(response.toString());
            JSONArray Array_out = Json_out.getJSONArray("data");
            
            //System.out.println(obj_JSONArray);
            JSONObject obj_JSONObject2 = obj_JSONArray.getJSONObject(0);
            JSONObject Json_out2 = Array_out.getJSONObject(0);
            
            JSONArray address_components_array = obj_JSONObject2.getJSONArray("status2");
            JSONArray Array_out2 = Json_out2.getJSONArray("data2");
            
            JSONObject obj_JSONObject3 = address_components_array.getJSONObject(0);
            JSONObject Json_out3 = Array_out2.getJSONObject(0);
            
            login = obj_JSONObject3.getString("status3");
            active = obj_JSONObject3.getString("log");
            nama = Json_out3.getString("name");
            
            //Cek Hasil Dari Pemanggilan
            System.out.println("Nama :  " + Json_out3.getString("name"));
            System.out.println("Actvie :  " + Json_out3.getString("log"));
            System.out.println(getnamepc());
            
            if(login.equals("berhasil") && active.equals("1")){
                saran = JOptionPane.showInputDialog(this, "Masukkan Saran Penggunaan Komputer");
                datatoweb(""+nim,getnamepc(),"0",""+saran);
                formLogin start = new formLogin();;
                start.setVisible(true);
                this.dispose();
            }else{
                //System.out.println("Maaf data Tidak Valid, pengecekan data  " +login+ " status active " +active);
                
                }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                formUtama utm = new formUtama();
                utm.pack();
                utm.setSize(300, 500);
                utm.setLocationRelativeTo(null);
                utm.setVisible(true);
            }

            private void setUndecorated(boolean b) {
                throw new UnsupportedOperationException("Not supported yet."); 
            //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public static final javax.swing.JLabel txtnama = new javax.swing.JLabel();
    public static final javax.swing.JLabel txtnim = new javax.swing.JLabel();
    public static final javax.swing.JLabel txtpass = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
